name: Analyze HTML/CSS

on:
  push:
    branches:
      - new
  pull_request:
    branches:
      - new

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      # Étape 1 : Checkout du code
      - name: Checkout repository
        uses: actions/checkout@v3

      # Étape 2 : Installer Node.js (nécessaire pour installer les outils)
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      # Étape 3 : Installer les dépendances
      - name: Install dependencies
        run: |
          npm install -g stylelint stylelint-config-standard htmlhint

      # Étape 4 : Analyser le CSS avec Stylelint
      - name: Run Stylelint (CSS)
        run: |
          stylelint "**/*.css"

      # Étape 5 : Analyser le HTML avec HTMLHint
      - name: Run HTMLHint (HTML)
        run: |
          htmlhint "**/*.html"
